# Generated by Django 5.0.6 on 2024-07-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_size_product_sizes_alter_size_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('users', models.IntegerField()),
                ('new_clients', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('website_views', models.IntegerField()),
                ('daily_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_tasks', models.IntegerField()),
            ],
        ),
    ]
