# Generated by Django 5.0.6

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

def backup_existing_products(apps, schema_editor):
    """Backup existing product data before migration"""
    Product = apps.get_model('store', 'Product')
    
    # Create a temporary backup table with existing data
    for product in Product.objects.all():
        # Store price in original_price field
        if hasattr(product, 'price'):
            product.original_price = product.price
        
        # Set default values for new required fields
        if not hasattr(product, 'sku') or not product.sku:
            product.sku = f'SKU-{product.id:08d}'
        
        if not hasattr(product, 'stock_quantity'):
            product.stock_quantity = 10  # Default stock
            
        if not hasattr(product, 'created_at'):
            product.created_at = timezone.now()
            
        # Copy image to main_image if exists
        if hasattr(product, 'image') and product.image:
            product.main_image = product.image

def reverse_backup(apps, schema_editor):
    """Reverse the backup operation"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        # First, add new models without dependencies
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='Color hex code (e.g., #FF0000)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        
        # Add new fields to existing models with nullable/default values first
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        
        # Add new fields to Size
        migrations.AddField(
            model_name='size',
            name='us_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='uk_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='eu_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        
        # Update Meta options
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name'], 'verbose_name_plural': 'sizes'},
        ),
        
        # Run data backup function
        migrations.RunPython(backup_existing_products, reverse_backup),
    ]
