# Generated by Django 5.0.6

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import uuid

def create_default_brand(apps, schema_editor):
    """Create a default brand for existing products"""
    Brand = apps.get_model('store', 'Brand')
    default_brand, created = Brand.objects.get_or_create(
        name='Unbranded',
        defaults={
            'slug': 'unbranded',
            'description': 'Default brand for existing products',
            'is_active': True
        }
    )
    return default_brand.id

def migrate_product_data(apps, schema_editor):
    """Migrate existing product data to new structure"""
    Product = apps.get_model('store', 'Product')
    Brand = apps.get_model('store', 'Brand')
    
    # Get or create default brand
    default_brand_id = create_default_brand(apps, schema_editor)
    
    for product in Product.objects.all():
        # Set brand (convert string to brand object)
        if hasattr(product, 'brand') and isinstance(product.brand, str):
            brand_name = product.brand
            brand, created = Brand.objects.get_or_create(
                name=brand_name,
                defaults={
                    'slug': brand_name.lower().replace(' ', '-'),
                    'description': f'Brand: {brand_name}',
                    'is_active': True
                }
            )
            product.brand_id = brand.id
        else:
            product.brand_id = default_brand_id
        
        # Set default values for new fields
        if not hasattr(product, 'original_price') or not product.original_price:
            if hasattr(product, 'price'):
                product.original_price = product.price
            else:
                product.original_price = 0
        
        if not hasattr(product, 'sku') or not product.sku:
            product.sku = f'SKU-{uuid.uuid4().hex[:8].upper()}'
        
        if not hasattr(product, 'stock_quantity'):
            product.stock_quantity = 10
        
        if not hasattr(product, 'created_at'):
            product.created_at = timezone.now()
        
        if not hasattr(product, 'updated_at'):
            product.updated_at = timezone.now()
        
        # Copy image to main_image
        if hasattr(product, 'image') and product.image:
            product.main_image = product.image
        
        product.save()

def reverse_migrate_product_data(apps, schema_editor):
    """Reverse the product data migration"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_backup_existing_products'),
    ]

    operations = [
        # Add new Product fields that can be nullable first
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5, help_text='Minimum stock level for alerts'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/', null=True, blank=True),
        ),
        
        # Run data migration
        migrations.RunPython(migrate_product_data, reverse_migrate_product_data),
        
        # Make required fields non-nullable after data migration
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Change brand field from CharField to ForeignKey
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand', null=True, blank=True),
        ),
        
        # Update category field
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
        
        # Update status field choices
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Còn hàng'), ('out_of_stock', 'Hết hàng'), ('discontinued', 'Ngừng kinh doanh'), ('coming_soon', 'Sắp ra mắt')], default='active', max_length=20),
        ),
        
        # Update Product Meta options
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'products'},
        ),
    ]
